gui:
  nerdFontsVersion: "3"
git:
  mainBranches:
    - master
    - main
    - development
  autoFetch: false
  autoForwardBranches: none
  branchLogCmd: git log --graph --color=always --pretty=format:'%C(auto)%h %C(cyan)(%ad) %C(white)%s %C(cyan)by %an %C(auto)%d' --date=format-local:'%Y/%m/%d %H:%M' --decorate {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --color=always --pretty=format:'%C(cyan)(%ad) %C(white)%s %C(cyan)by %an %C(auto)%d' --date=format-local:'%Y/%m/%d %H:%M' --branches --
  parseEmoji: true
keybinding:
  universal:
    quit: <C-c>
    nextTab: l
    prevTab: h
    nextBlock-alt: <tab>
    prevBlock-alt: <backtab>

